<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/aula.gruporo.com.mx
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date 15 de febrero de 2018 a las 19:27
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLANNGenDate is an internal mark
   $CLANNGenDate = "1518722855";

/* announcementPortletMaxItems : Use 0 to display all */
$GLOBALS['announcementPortletMaxItems'] = 3;



?>