<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/aula.gruporo.com.mx
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date 15 de febrero de 2018 a las 19:27
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLDSCGenDate is an internal mark
   $CLDSCGenDate = "1518722855";

/* cldsc_use_new_ordering_of_labels : Display description elements corresponding to others at the end */
$GLOBALS['cldsc_use_new_ordering_of_labels'] = FALSE;



?>