<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/aula.gruporo.com.mx
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date 15 de febrero de 2018 a las 19:27
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLGRPGenDate is an internal mark
   $CLGRPGenDate = "1518722855";

/* multiGroupAllowed : Allow teachers to subscribe a user in several groups */
$GLOBALS['multiGroupAllowed'] = TRUE;


/* tutorCanBeSimpleMemberOfOthersGroupsAsStudent : A tutor attached to a group can subscribe himself to another group as a simple user. */
$GLOBALS['tutorCanBeSimpleMemberOfOthersGroupsAsStudent'] = FALSE;


/* showTutorsInGroupList : Not implemented, name reserved  for future version of Claroline */
$GLOBALS['showTutorsInGroupList'] = FALSE;


/* clgrp_displayMyGroups : Display "my groups" above group list */
$GLOBALS['clgrp_displayMyGroups'] = TRUE;



?>