<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/aula.gruporo.com.mx
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date 15 de febrero de 2018 a las 19:27
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLKCACHEGenDate is an internal mark
   $CLKCACHEGenDate = "1518722855";

/* cache_lifeTime : Time to keep a cache as valid */
$GLOBALS['cache_lifeTime'] = 10;


/* cache_automaticCleaningFactor : write n-1 times without check if (others) cached files are or not deprecated */
$GLOBALS['cache_automaticCleaningFactor'] = 40;



?>