<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/aula.gruporo.com.mx
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date 15 de febrero de 2018 a las 19:27
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLMSGGenDate is an internal mark
   $CLMSGGenDate = "1518722855";

/* messagePerPage : Number of message per page */
$GLOBALS['messagePerPage'] = 15;


/* mailNotification : Enable Email notification */
$GLOBALS['mailNotification'] = TRUE;


/* userCanSendMessage : Users can send messages from outside a course context */
$GLOBALS['userCanSendMessage'] = FALSE;



?>