<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/aula.gruporo.com.mx
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date 15 de febrero de 2018 a las 19:27
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLQWZGenDate is an internal mark
   $CLQWZGenDate = "1518722855";

/* enableExerciseExportQTI : Enable IMS-QTI Export */
$GLOBALS['enableExerciseExportQTI'] = TRUE;


/* exercisesPerPage : Number of exercises per page */
$GLOBALS['exercisesPerPage'] = 25;


/* showAllFeedbacks : If activated, all the feedbacks will be shown to users; if not, only those corresponding to the selected or correct answers will be displayed */
$GLOBALS['showAllFeedbacks'] = FALSE;


/* allow_exercise_event_generation : Automatically insert an event in the calendar at the end date */
$GLOBALS['allow_exercise_event_generation'] = TRUE;



?>