<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/aula.gruporo.com.mx
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date 15 de febrero de 2018 a las 19:27
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLRSSGenDate is an internal mark
   $CLRSSGenDate = "1518722855";

/* enableRssInCourse : Enable RSS in course */
$GLOBALS['enableRssInCourse'] = TRUE;


/* rssRepositoryCache : Note :  this repository should be protected with a .htaccess or       be placed outside the web. Because there contain data of private courses. */
$GLOBALS['rssRepositoryCache'] = 'tmp/cache/rss/';


/* rssUseCache : Enabling the cache may increase performance */
$GLOBALS['rssUseCache'] = TRUE;


/* rssCacheLifeTime : Time before really compute data. 86400 = 1 day. */
$GLOBALS['rssCacheLifeTime'] = 86400;



?>